/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package crawella;

import java.io.IOException;

import crawella.exception.InvalidCommandArgumentException;
import crawella.file.FileHandler;
import crawella.web.Crawler;

public class Crawella {
    public static void main(String[] args) {
			try {
				ApplicationHelper.parseArgs(args);
				Crawler crawler = new Crawler();
	
				new FileHandler().write(Crawler.LINKS_FILE, "");

				crawler.crawl("https://en.wikipedia.org/", ApplicationHelper.getDepthArg());
			} catch (InvalidCommandArgumentException | IOException e) {
				e.printStackTrace();
			}
    }
}
